version: '3'

services:

  bot:
    container_name: pepebot.bot
    build: .
    ports:
      - 9001:9001
    restart: always
    networks:
      - pepebot

  db:
    image: mongo:latest
    container_name: pepebot.db
    environment:
      - MONGO_INITDB_DATABASE=pepebot
      - MONGO_INITDB_ROOT_USERNAME=service
      - MONGO_INITDB_ROOT_PASSWORD=CX66qXYmS8xsLxBxZkMqDHwr
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data/db
    restart: always
    networks:
      - pepebot

volumes:
  cdn:

networks:
  pepebot:
    driver: bridge