version: '3'

services:

  bot:
    container_name: pepebot.bot
    image: iamalirezaj/pepebot:latest
    restart: always
    ports:
      - 9001:9001
    volumes:
      - $PWD/db/data:/data
      - $PWD/config.hcl:/config/config.hcl
