name: Run go tests

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Go get packages
      run: go get .

    - name: Run go tests
      run: go test ./tests -v -race
